<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="68" started-at="2018-05-31T09:24:10Z" finished-at="2018-05-31T09:24:10Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="68" started-at="2018-05-31T09:24:10Z" finished-at="2018-05-31T09:24:10Z">
      <class name="SystemRun.System1">
        <test-method status="FAIL" signature="Start()[pri:0, instance:SystemRun.System1@11438d26]" name="Start" is-config="true" duration-ms="39" started-at="2018-05-31T09:24:10Z" finished-at="2018-05-31T09:24:10Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.relevantcodes.extentreports.markup.Content.renewSystemInfo(Content.java:45)
at com.relevantcodes.extentreports.markup.DocumentConfig.renewSystemInfo(DocumentConfig.java:180)
at com.relevantcodes.extentreports.ExtentReports.initialProc(ExtentReports.java:310)
at com.relevantcodes.extentreports.ExtentReports.init(ExtentReports.java:305)
at com.relevantcodes.extentreports.ExtentReports.init(ExtentReports.java:263)
at com.relevantcodes.extentreports.ExtentReports.init(ExtentReports.java:246)
at SystemRun.System1.Start(System1.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.TestRunner.beforeRun(TestRunner.java:529)
at org.testng.TestRunner.run(TestRunner.java:497)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Start -->
        <test-method status="SKIP" signature="case1()[pri:0, instance:SystemRun.System1@11438d26]" name="case1" duration-ms="0" started-at="2018-05-31T09:24:10Z" finished-at="2018-05-31T09:24:10Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.relevantcodes.extentreports.markup.Content.renewSystemInfo(Content.java:45)
at com.relevantcodes.extentreports.markup.DocumentConfig.renewSystemInfo(DocumentConfig.java:180)
at com.relevantcodes.extentreports.ExtentReports.initialProc(ExtentReports.java:310)
at com.relevantcodes.extentreports.ExtentReports.init(ExtentReports.java:305)
at com.relevantcodes.extentreports.ExtentReports.init(ExtentReports.java:263)
at com.relevantcodes.extentreports.ExtentReports.init(ExtentReports.java:246)
at SystemRun.System1.Start(System1.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.TestRunner.beforeRun(TestRunner.java:529)
at org.testng.TestRunner.run(TestRunner.java:497)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case1 -->
      </class> <!-- SystemRun.System1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
